version: '2.27.0'

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres